name: solr
title: Solr
icon: solr

services:
- name: solr
  title: Solr
  service: solr
  links:
  - name: zookeeper
    service: zookeeper
- name: zookeeper
  title: ZooKeeper
  service: zookeeper
  volumes:
  - name: data 
    size: 1
